name: Adds all issues to GeoDMS project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: v13/workflows/actions
        with:
          project-url: https://github.com/orgs/ObjectVision/projects/4
          github-token: ${{ secrets.NEWISSUESTOBOARD }}
